# Travis build integration.
# https://docs.travis-ci.com/
language: c
sudo: false
git:
  depth: false
addons:
  apt:
    update: true
    config:
      retries: true
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - gcc-{4.4,8}
    - clang-{3.5,7}
compiler:
- gcc-8
- clang-7
- gcc-4.4
- clang-3.5
script: ./nginx-zero ${TRAVIS_COMMIT_MESSAGE%%:*}
